/* THE HOUSE MOSAIC — a full-bleed collage backdrop.
 *
 * Extracted from the /mockup/collection-collage comp, where it was the part everyone
 * actually liked. It is now a production surface (it backs the 404), so it lives here
 * rather than inside a section that is documented as throwaway.
 *
 * Four layers, in order: the mosaic, a champagne grade, a radial GROUND scrim that keeps
 * the centre legible while the collage bleeds in at the edges, and a grain film. The
 * scrim fades to whatever `--ground` currently is, so the whole thing re-resolves for the
 * night scheme instead of painting an ivory fog over it.
 *
 * Purely decorative — aria-hidden throughout, and it renders no text. Whatever sits on
 * top owns the page's meaning.
 *
 * The tiles are 520px derivatives generated by scripts/make-collage-tiles.mjs, not the
 * live assets: twelve full-resolution photographs is 1.74MB, and the 404 is the one page
 * a visitor never chose to load. Regenerate after replacing any source photograph.
 */

import "./collage-backdrop.css";

const IMAGES = [
  "/collage/hero.webp",
  "/collage/index-lead.webp",
  "/collage/essay-1-patience.webp",
  "/collage/essay-2-towns.webp",
  "/collage/essay-3-heat.webp",
  "/collage/origin-bg.webp",
  "/collage/journal.webp",
  "/collage/banner-1.webp",
  "/collage/reveal-desktop.webp",
  "/collage/mon-amour.webp",
  "/collage/don-amour.webp",
  "/collage/don-amour-notes-grid.webp",
];

/* Enough cells to cover a tall viewport; a few span two so the grid reads as a collage
   rather than a contact sheet. The modulus offsets are chosen to not line up — 5 and 7
   are coprime, so the spans never settle into a visible stripe. */
const TILES = Array.from({ length: 48 }, (_, i) => ({
  key: i,
  src: IMAGES[i % IMAGES.length],
  span: i % 5 === 0 ? "s2r" : i % 7 === 3 ? "s2c" : "",
}));

export default function CollageBackdrop() {
  return (
    <>
      <div className="cb__collage" aria-hidden="true">
        {TILES.map((t) => (
          <figure className={`cb__tile ${t.span}`} key={t.key}>
            {/* No `loading="lazy"`: every cell is above the fold by construction, and a
                lazy tile pops in after the scrim has already settled. */}
            <img src={t.src} alt="" />
          </figure>
        ))}
      </div>
      <div className="cb__tint" aria-hidden="true" />
      <div className="cb__scrim" aria-hidden="true" />
      <div className="cb__grain" aria-hidden="true" />
    </>
  );
}
